// backend/test/unit/sc-data-load-ops.test.ts
//
// Adding one sample-data CSV to its EXISTING SC_Data table. The load's whole job is
// to be safe on a table that already holds data — it never creates, drops or empties
// anything, and a row whose uid is already there is left out — so most of what is
// tested here is what does NOT happen: rows not doubled, rows not sent blind, a staged
// temp file not left behind, a count not taken on trust.
//
// IRIS is the fake in `helpers/fake-sc-data-iris.ts`, which simulates the behaviour
// measured on the real instance (LOAD DATA reads the staged file, skips a duplicate
// primary key without complaining). The real statement is covered by the live
// integration test.
import { describe, it, expect } from 'vitest';
import {
  LOAD_TIMEOUT_MS,
  MAX_CSV_ROWS,
  UID_PROBE_CHUNK,
  buildLoadDataSql,
  buildStagedCsv,
  csvCell,
  csvRow,
  describeScDataTable,
  loadScDataCsv,
  planScDataColumns,
  unmatchedHeaders,
  type ScDataLoadDeps,
  type ScDataTableInfo,
} from '../../src/iris/sc-data-load-ops.js';
import {
  createFakeScDataIris,
  DEFAULT_TABLES,
  type FakeScDataIris,
  type FakeScDataOptions,
} from './helpers/fake-sc-data-iris.js';

/**
 * What the route hands the loader per file: the CSV's name (for the report and the error
 * messages) and the table its name resolved to. Nothing else — a header is matched
 * against the installed columns, so there is no per-file configuration to pass.
 */
const CARRIERS = { file: 'carriers.csv', table: 'Carrier' };
const LOCATIONS = { file: 'locations.csv', table: 'Location' };

/**
 * A table description, as INFORMATION_SCHEMA would give it: the listed columns are
 * writable, plus the read-only trio every SC_Data table really has. Every column is a
 * VARCHAR unless `types` says otherwise, which is true of nearly all of SC_Data.
 */
function tableInfo(
  table: string,
  columns: string[],
  readOnly = READ_ONLY,
  types: Record<string, string> = {},
): ScDataTableInfo {
  const map = (names: readonly string[]) => new Map(names.map((c) => [c.toLowerCase(), c]));
  const all = [...columns, ...readOnly];
  return {
    table,
    columns: map(all),
    writable: map(columns),
    types: new Map(all.map((c) => [c.toLowerCase(), (types[c] ?? 'VARCHAR').toUpperCase()])),
  };
}

/** Real columns a load must never write to (identity / generated). */
const READ_ONLY = ['ID', 'lastUpdatedTime', 'recordCreatedTime'];

/** Load one CSV against a fresh fake, returning both the result and the fake. */
async function load(
  csv: string,
  target: { file: string; table: string } = CARRIERS,
  options: FakeScDataOptions = {},
) {
  const iris = createFakeScDataIris(options);
  const result = await loadScDataCsv(iris.deps, { ...target, csv });
  return { result, iris };
}

/**
 * The Error a load rejected with, so a test can examine the WHOLE message instead of
 * matching one pattern at a time — which is what a test about the DIAGNOSIS has to do:
 * what the message now says, and what it no longer says.
 */
async function failedLoad(
  iris: FakeScDataIris,
  target: { file: string; table: string } = CARRIERS,
  csv: string = CARRIER_CSV,
): Promise<Error> {
  return loadScDataCsv(iris.deps, { ...target, csv }).then(
    () => {
      throw new Error('Expected the load to fail.');
    },
    (err: unknown) => err as Error,
  );
}

/** The staged file's lines (it always ends with a newline, which split leaves empty). */
function stagedLines(text: string | undefined): string[] {
  return (text ?? '').replace(/\n$/, '').split('\n');
}

const CARRIER_CSV = 'ID,Name,Type,Status\nCAR-1,Speedy,Road,Active\nCAR-2,Air1,Air,Active\n';

describe('describeScDataTable', () => {
  it('reports the table and its columns AS IRIS SPELLS THEM, matched case-insensitively', async () => {
    // The product spells some columns differently from its own class definition
    // (customerID vs customerId), so the names that go into the statement have to come
    // from IRIS rather than from the file's header or from anything here.
    const iris = createFakeScDataIris({ tables: { SalesShipment: ['uid', 'customerID', 'status'] } });
    const info = await describeScDataTable(iris.deps.sql, 'salesshipment');

    expect(info?.table).toBe('SalesShipment');
    expect(info?.columns.get('customerid')).toBe('customerID');
  });

  it('separates the columns a load may WRITE from the ones it may only read', async () => {
    const iris = createFakeScDataIris();
    const info = await describeScDataTable(iris.deps.sql, 'Carrier');

    // The trio is really there…
    expect([...(info?.columns.keys() ?? [])]).toEqual(
      expect.arrayContaining(['id', 'lastupdatedtime', 'recordcreatedtime']),
    );
    // …and none of it may be written: ID is the identity column, the two timestamps are
    // generated by the product.
    expect([...(info?.writable.keys() ?? [])]).toEqual(['uid', 'name', 'type', 'status']);
  });

  it('is undefined when the namespace has no such table', async () => {
    const iris = createFakeScDataIris({ tables: { Carrier: null } });
    expect(await describeScDataTable(iris.deps.sql, 'Carrier')).toBeUndefined();
  });
});

describe('planScDataColumns', () => {
  const info = tableInfo('Carrier', DEFAULT_TABLES.Carrier as string[]);

  it('pairs each header with the column of that name, ignoring case and surrounding spaces', () => {
    const plans = planScDataColumns('carriers.csv', [' id ', 'NAME', 'type', 'Status'], info);
    expect(plans.map((p) => [p.column, p.index])).toEqual([
      ['uid', 0],
      ['name', 1],
      ['type', 2],
      ['status', 3],
    ]);
  });

  it('pairs by header NAME, so the file\'s column order does not matter', () => {
    // Columns are matched by name and read by the index that name sits at, so a set
    // whose files were exported with the columns in another order still loads. The
    // plan comes back with the key first, whatever the file's order is.
    const plans = planScDataColumns('carriers.csv', ['Status', 'Type', 'Name', 'ID'], info);
    expect(plans.map((p) => [p.column, p.index])).toEqual([
      ['uid', 3],
      ['status', 0],
      ['type', 1],
      ['name', 2],
    ]);
  });

  it('ignores a header no column of the table has, wherever it sits in the file', () => {
    // An extra column in the middle must not shift the ones after it.
    const plans = planScDataColumns(
      'carriers.csv',
      ['ID', 'Comment', 'Name', 'Type', 'Status'],
      info,
    );
    expect(plans.map((p) => [p.column, p.index])).toEqual([
      ['uid', 0],
      ['name', 2],
      ['type', 3],
      ['status', 4],
    ]);
  });

  it('LOADS any column the installed table has, including ones no shipped file carries', () => {
    // SC_Data.Location really has region/latitude/longitude. A set exported out of
    // SC_Data — or a shipped file someone added a column to — must get those values in
    // rather than have them dropped, without anything here being told they exist.
    const rich = tableInfo('Location', [...(DEFAULT_TABLES.Location as string[]), 'region', 'latitude']);
    const plans = planScDataColumns('locations.csv', ['ID', 'Name', 'latitude', 'Region'], rich);

    // The key first, then the leftovers in the file's own order.
    expect(plans.map((p) => [p.column, p.index])).toEqual([
      ['uid', 0],
      ['name', 1],
      ['latitude', 2],
      ['region', 3],
    ]);
    // Spelled as IRIS spells the column, not as the file spelled the header.
    expect(plans.map((p) => p.column)).toContain('region');
  });

  it('NEVER writes the identity ID or a generated timestamp, however the CSV names them', () => {
    // These columns exist, so they cannot be refused on absence: ID is filled by
    // $i(^SC.Data.CarrierD) and recordCreatedTime is read-only after insert.
    const plans = planScDataColumns(
      'carriers.csv',
      ['UID', 'Name', 'ID', 'lastUpdatedTime', 'RecordCreatedTime'],
      info,
    );
    expect(plans.map((p) => p.column)).toEqual(['uid', 'name']);
  });

  it('takes UID for the key wherever it sits, and does not send the key twice', () => {
    // A file with both spellings means two different things by them, and either way round
    // the business key must win — see KEY_HEADERS.
    for (const header of [['ID', 'UID', 'Name'], ['UID', 'ID', 'Name']]) {
      const plans = planScDataColumns('carriers.csv', header, info);
      expect(plans.filter((p) => p.column === 'uid'), header.join()).toHaveLength(1);
      expect(plans.find((p) => p.column === 'uid')?.index, header.join()).toBe(
        header.indexOf('UID'),
      );
    }
  });

  it('leaves out a column the file has no header for, instead of failing the file', () => {
    // demandPlan.csv legitimately has no quantityUom; refusing its 738 rows over one
    // absent optional column would serve nobody.
    const demandInfo = tableInfo('DemandPlan', DEFAULT_TABLES.DemandPlan as string[]);
    const plans = planScDataColumns(
      'demandPlan.csv',
      ['ID', 'productId', 'locationId', 'startDate', 'quantity'],
      demandInfo,
    );
    expect(plans.map((p) => p.column)).toEqual([
      'uid',
      'productId',
      'locationId',
      'startDate',
      'quantity',
    ]);
  });

  it('DROPS a column the installed table does not have, so nothing is sent blind', () => {
    const older = tableInfo('Carrier', ['uid', 'name']);
    const plans = planScDataColumns('carriers.csv', ['ID', 'Name', 'Type', 'Status'], older);
    expect(plans.map((p) => p.column)).toEqual(['uid', 'name']);
  });

  it('reads a repeated header from its FIRST column', () => {
    const plans = planScDataColumns('carriers.csv', ['ID', 'Name', 'name'], info);
    expect(plans.find((p) => p.column === 'name')?.index).toBe(1);
  });

  it('THROWS when the file has no uid header — those rows have no key at all', () => {
    expect(() => planScDataColumns('carriers.csv', ['Name', 'Type'], info)).toThrow(
      /carriers\.csv has no UID or ID column/,
    );
  });

  it('THROWS when the table itself has no uid column', () => {
    const keyless = tableInfo('Carrier', ['name', 'type']);
    expect(() => planScDataColumns('carriers.csv', ['ID', 'Name'], keyless)).toThrow(
      /no UID or ID column/,
    );
  });
});

describe('unmatchedHeaders', () => {
  const info = tableInfo('Carrier', DEFAULT_TABLES.Carrier as string[]);
  const left = (header: string[]) =>
    unmatchedHeaders(header, planScDataColumns('carriers.csv', header, info));

  it('names the columns whose values did not load, and nothing else', () => {
    // The table has no `Comment` column, so those values went nowhere. Reporting it is
    // the whole point: a header that lands nowhere is invisible otherwise, and with every
    // column resolved by name a respelled header is exactly what that looks like.
    expect(left(['ID', 'Comment', 'Name', 'Type', 'Status'])).toEqual(['Comment']);
  });

  it('is empty when every header found a column', () => {
    expect(left(['ID', 'Name', 'Type', 'Status'])).toEqual([]);
  });

  it('reports a header the file spells wrong, which is what a renamed column looks like', () => {
    expect(left(['ID', 'Nmae', 'Type', 'Status'])).toEqual(['Nmae']);
  });

  it('reports the columns a load must never write to — they did not load either', () => {
    // `ID` here is the identity column, not the key: the key pass took `UID`. Saying so is
    // honest — those values were not stored.
    expect(left(['UID', 'Name', 'ID', 'recordCreatedTime'])).toEqual(['ID', 'recordCreatedTime']);
  });

  it('keeps the file\'s own spelling and order, once each, ignoring blanks', () => {
    expect(left(['ID', ' Extra ', 'Name', 'EXTRA', '', '   ', 'Other'])).toEqual([
      'Extra',
      'Other',
    ]);
  });

  it('does not report the key header, whichever spelling loaded it', () => {
    // `ID` fed `uid`, so it is not "left over" — reporting it would send whoever reads the
    // report looking for a column that did load.
    expect(left(['ID', 'Name'])).toEqual([]);
    expect(left(['UID', 'Name'])).toEqual([]);
  });
});

describe('the staged CSV', () => {
  it('quotes a cell only when it must, and doubles an embedded quote', () => {
    expect(csvCell('Speedy')).toBe('Speedy');
    expect(csvCell('')).toBe('');
    expect(csvCell('34.75, 113.68')).toBe('"34.75, 113.68"');
    expect(csvCell('say "hi"')).toBe('"say ""hi"""');
    expect(csvCell('two\nlines')).toBe('"two\nlines"');
    expect(csvRow(['a', 'b,c', ''])).toBe('a,"b,c",');
  });

  it('leads with the TARGET column names and ends with a newline', () => {
    // The header is rewritten to the target columns precisely so no header spelling,
    // space or case can reach the SQL statement.
    const text = buildStagedCsv(['uid', 'name'], [['CAR-1', 'Speedy']]);
    expect(text).toBe('uid,name\nCAR-1,Speedy\n');
    expect(buildStagedCsv(['uid'], [])).toBe('uid\n');
  });
});

describe('buildLoadDataSql', () => {
  it('quotes the table and every column on BOTH sides, and asks IRIS to skip the header', () => {
    expect(buildLoadDataSql('/tmp/x/Location.csv', 'Location', ['uid', 'postalCode'])).toBe(
      'LOAD DATA FROM FILE \'/tmp/x/Location.csv\' INTO SC_Data."Location"("uid","postalCode") ' +
        'VALUES ("uid","postalCode") USING {"from":{"file":{"header":"1"}}}',
    );
  });
});

describe('loadScDataCsv', () => {
  it('adds the file\'s rows to the existing table and reports what landed', async () => {
    const { result, iris } = await load(CARRIER_CSV);

    expect(result).toEqual({
      loaded: true,
      table: 'Carrier',
      columns: ['uid', 'name', 'type', 'status'],
      rows: 2,
      skippedRows: 0,
      orphanRows: 0,
      // Every header of this file found a column, so nothing was left behind.
      ignoredHeaders: [],
      totalRows: 2,
    });
    expect(iris.rows('Carrier')).toEqual(['CAR-1', 'CAR-2']);
    // Nothing was created, dropped or emptied — only a load ran.
    expect(iris.sql.some((s) => /^(CREATE|DROP|DELETE|TRUNCATE|ALTER)/i.test(s))).toBe(false);
  });

  it('stages the rows with the target header, then DELETES the file from IRIS', async () => {
    const { iris } = await load(CARRIER_CSV);

    expect(stagedLines(iris.staged('Carrier'))).toEqual([
      'uid,name,type,status',
      'CAR-1,Speedy,Road,Active',
      'CAR-2,Air1,Air,Active',
    ]);
    // The user's data must not be left lying in a temp file inside their IRIS.
    expect([...iris.files.keys()]).toEqual([]);
  });

  it('SKIPS a row whose uid the table already holds, and loads the rest', async () => {
    // The user's rule for a re-load, verbatim: "if a UID exists ignore that row and
    // continue with the others".
    const { result, iris } = await load(CARRIER_CSV, CARRIERS, { existing: { Carrier: ['CAR-1'] } });

    expect(result).toMatchObject({ loaded: true, rows: 1, skippedRows: 1, totalRows: 2 });
    expect(iris.rows('Carrier')).toEqual(['CAR-1', 'CAR-2']);
    // Only the new row was even sent.
    expect(stagedLines(iris.staged('Carrier'))).toEqual(['uid,name,type,status', 'CAR-2,Air1,Air,Active']);
  });

  it('loads a file whose columns are in a DIFFERENT ORDER, values still in the right column', async () => {
    // The values here are deliberately distinguishable: if the load were positional,
    // "Road" would land in `status` and "Active" in `type` without any error at all —
    // the tables would just be quietly wrong.
    const csv = 'Status,Type,Name,ID\nActive,Road,Speedy,CAR-1\n';
    const { result, iris } = await load(csv);

    // The key is staged first and the rest keep the FILE's order, which is fine because the
    // LOAD DATA column list names each one: what matters is that every value stays under
    // its own column, so `Road` is the type and `Active` the status either way.
    expect(result).toMatchObject({
      loaded: true,
      rows: 1,
      skippedRows: 0,
      totalRows: 1,
      columns: ['uid', 'status', 'type', 'name'],
    });
    expect(stagedLines(iris.staged('Carrier'))).toEqual([
      'uid,status,type,name',
      'CAR-1,Active,Road,Speedy',
    ]);
  });

  it('ignores an extra column in the middle instead of shifting the rest', async () => {
    const csv = 'ID,Comment,Name,Type,Status\nCAR-1,ignore me,Speedy,Road,Active\n';
    const { iris } = await load(csv);

    expect(stagedLines(iris.staged('Carrier'))).toEqual([
      'uid,name,type,status',
      'CAR-1,Speedy,Road,Active',
    ]);
  });

  it('loads an ADDED column the table has, and still ignores one it does not', async () => {
    // The question this answers: a CSV grows a column that already exists in SC_Data.
    // It has to land — reporting the file as loaded while dropping those values would
    // be the worst outcome.
    const csv = 'ID,Name,Type,Status,region,nonsense\nCAR-1,Speedy,Road,Active,EMEA,ignore me\n';
    const { result, iris } = await load(csv, CARRIERS, {
      tables: { Carrier: ['uid', 'name', 'type', 'status', 'region'] },
    });

    expect(result).toMatchObject({ loaded: true, rows: 1 });
    expect(stagedLines(iris.staged('Carrier'))).toEqual([
      'uid,name,type,status,region',
      'CAR-1,Speedy,Road,Active,EMEA',
    ]);
    // The unknown header is not in the statement at all.
    expect(iris.loads()[0]).not.toContain('nonsense');
  });

  it('loads an SC_Data export, whose ID is the ROW ID and whose uid is the key', async () => {
    // The file has both columns and means different things by them. `uid` is the key,
    // and `ID` — the identity column — is not sent at all: the row gets its own from
    // $i(^SC.Data.CarrierD).
    const csv = 'ID,uid,Name,Type,Status\n47,CAR-1,Speedy,Road,Active\n';
    const { iris } = await load(csv);

    expect(iris.rows('Carrier')).toEqual(['CAR-1']);
    expect(stagedLines(iris.staged('Carrier'))).toEqual([
      'uid,name,type,status',
      'CAR-1,Speedy,Road,Active',
    ]);
    expect(iris.loads()[0]).not.toContain('"ID"');
  });

  it('reads the key from a UID header just as well as from ID', async () => {
    // A set exported out of SC_Data names the key column after the column itself. It
    // must load, and the skip-what-is-already-there check must key off it too.
    const csv = 'UID,Name,Type,Status\nCAR-1,Speedy,Road,Active\nCAR-2,Air1,Air,Active\n';
    const { result, iris } = await load(csv, CARRIERS, { existing: { Carrier: ['CAR-1'] } });

    expect(result).toMatchObject({ loaded: true, rows: 1, skippedRows: 1, totalRows: 2 });
    // Staged under the TARGET column name, whichever spelling the file used.
    expect(stagedLines(iris.staged('Carrier'))).toEqual([
      'uid,name,type,status',
      'CAR-2,Air1,Air,Active',
    ]);
  });

  it('reads the key from any casing of it — uid, Uid, ID', async () => {
    for (const header of ['uid', 'Uid', ' UID ', 'id', 'Id']) {
      const { result } = await load(`${header},Name,Type,Status\nCAR-9,Speedy,Road,Active\n`);
      expect(result, header).toMatchObject({ loaded: true, rows: 1, totalRows: 1 });
    }
  });

  it('prefers UID when a file carries BOTH ID and UID, whichever comes first', async () => {
    // The winner must be decided by NAME, not by column position — and it must be UID,
    // which is the business key in every file that has both.
    for (const csv of [
      'UID,ID,Name,Type,Status\nCAR-1,47,Speedy,Road,Active\n',
      'ID,UID,Name,Type,Status\n47,CAR-1,Speedy,Road,Active\n',
    ]) {
      const { iris } = await load(csv);
      expect(iris.rows('Carrier'), csv).toEqual(['CAR-1']);
    }
  });

  it('is repeatable: loading the same file twice does not double the rows', async () => {
    const iris = createFakeScDataIris();
    const first = await loadScDataCsv(iris.deps, { ...CARRIERS, csv: CARRIER_CSV });
    const second = await loadScDataCsv(iris.deps, { ...CARRIERS, csv: CARRIER_CSV });

    expect(first).toMatchObject({ rows: 2, skippedRows: 0 });
    expect(second).toMatchObject({ rows: 0, skippedRows: 2, totalRows: 2 });
    expect(iris.rows('Carrier')).toEqual(['CAR-1', 'CAR-2']);
    // With nothing to add, the second pass does not stage a file or run LOAD DATA.
    expect(iris.loads()).toHaveLength(1);
  });

  it('keeps the FIRST of two rows that share a uid inside the same file', async () => {
    const csv = 'ID,Name,Type,Status\nCAR-1,First,Road,Active\nCAR-1,Second,Air,Active\n';
    const { result, iris } = await load(csv);

    expect(result).toMatchObject({ rows: 1, skippedRows: 1, totalRows: 2 });
    expect(stagedLines(iris.staged('Carrier'))[1]).toBe('CAR-1,First,Road,Active');
  });

  it('skips a row with a blank uid — it could never satisfy the primary key', async () => {
    const csv = 'ID,Name,Type,Status\n,Nameless,Road,Active\n   ,Spacey,Road,Active\nCAR-2,Air1,Air,Active\n';
    const { result, iris } = await load(csv);

    expect(result).toMatchObject({ rows: 1, skippedRows: 2, totalRows: 3 });
    expect(iris.rows('Carrier')).toEqual(['CAR-2']);
  });

  it('ignores blank lines entirely rather than counting them as skipped rows', async () => {
    const csv = 'ID,Name,Type,Status\nCAR-1,Speedy,Road,Active\n\n,,,\nCAR-2,Air1,Air,Active\n';
    const { result } = await load(csv);
    expect(result).toMatchObject({ rows: 2, skippedRows: 0, totalRows: 2 });
  });

  it('pads a ragged row instead of shifting its later columns', async () => {
    const csv = 'ID,Name,Type,Status\nCAR-1,Speedy\n';
    const { result, iris } = await load(csv);
    expect(result).toMatchObject({ rows: 1 });
    expect(stagedLines(iris.staged('Carrier'))[1]).toBe('CAR-1,Speedy,,');
  });

  it('keeps a value that contains a comma as ONE value through staging', async () => {
    // locations.csv ships coordinates like "34.752687, 113.689948".
    const csv = 'ID,name,coordinates,postalCode\nLOC-1,Plant,"34.75, 113.68",\n';
    const { iris } = await load(csv, LOCATIONS);

    expect(stagedLines(iris.staged('Location'))).toEqual([
      'uid,name,coordinates,postalCode',
      'LOC-1,Plant,"34.75, 113.68",',
    ]);
  });

  it('reports a header-only file as zero rows rather than an error', async () => {
    const { result, iris } = await load('ID,Name,Type,Status\n');
    expect(result).toMatchObject({ loaded: true, rows: 0, skippedRows: 0, totalRows: 0 });
    expect(iris.loads()).toEqual([]);
  });

  it('SKIPS the file, without touching it, when the table is not installed here', async () => {
    // The user's rule: "if it does not exist then skip that csv and report it".
    const { result, iris } = await load(CARRIER_CSV, CARRIERS, { tables: { Carrier: null } });

    expect(result).toEqual({
      loaded: false,
      table: 'Carrier',
      reason: 'SC_Data.Carrier does not exist in this namespace, so carriers.csv was skipped.',
    });
    expect(iris.loads()).toEqual([]);
    expect(iris.files.size).toBe(0);
  });

  it('throws on a file with no header at all', async () => {
    await expect(load('')).rejects.toThrow(/carriers\.csv is empty/);
    await expect(load('\n\n')).rejects.toThrow(/carriers\.csv is empty/);
  });

  it('throws on a file whose header has no uid column', async () => {
    await expect(load('Name,Type\nSpeedy,Road\n')).rejects.toThrow(/has no UID or ID column/);
  });

  it('REFUSES a file over the row cap instead of loading a truncated prefix', async () => {
    const rows = Array.from({ length: MAX_CSV_ROWS }, (_, i) => `CAR-${i},N,Road,Active`);
    const csv = ['ID,Name,Type,Status', ...rows].join('\n') + '\n';
    await expect(load(csv)).rejects.toThrow(new RegExp(`more than ${MAX_CSV_ROWS - 1} rows`));
  });

  it('FAILS LOUDLY when fewer rows arrive than were sent', async () => {
    // LOAD DATA reports "Complete" even when it silently rejected rows, so the count
    // is read back — a claimed success with missing data is the worst outcome here.
    const dropOne = (rows: string[][]) => rows.slice(1);
    await expect(load(CARRIER_CSV, CARRIERS, { onLoad: dropOne })).rejects.toThrow(
      /Sent 2 row\(s\) to SC_Data\.Carrier, 1 loaded\. Data loading for this table failed\./,
    );
  });

  it('deletes the staged file even when the load itself fails', async () => {
    const { iris } = createFailingLoad();
    await expect(loadScDataCsv(iris.deps, { ...CARRIERS, csv: CARRIER_CSV })).rejects.toThrow(
      /SQLCODE -400/,
    );
    expect([...iris.files.keys()]).toEqual([]);
    // It really was staged first — the cleanup is not vacuous.
    expect(iris.staged('Carrier')).toContain('CAR-1');
  });

  it('propagates a connection failure so the route can stop the whole set', async () => {
    const boom = () => new Error('IRIS is unreachable (ECONNREFUSED)');
    await expect(
      load(CARRIER_CSV, CARRIERS, { failOn: /INFORMATION_SCHEMA/, throws: boom }),
    ).rejects.toThrow(/ECONNREFUSED/);
  });

  it('asks about the uids IN THE FILE, in bounded chunks, not about the whole table', async () => {
    // The cost has to scale with the CSV, not with however much real data the user's
    // table already holds — and the chunk stays under the Atelier wrapper's stack limit.
    const count = UID_PROBE_CHUNK * 2 + 5;
    const rows = Array.from({ length: count }, (_, i) => `CAR-${i},N,Road,Active`);
    const { result, iris } = await load(['ID,Name,Type,Status', ...rows].join('\n') + '\n');

    expect(result).toMatchObject({ rows: count });
    const probes = iris.sql.filter((s) => s.includes(' IN ('));
    expect(probes).toHaveLength(3);
    for (const probe of probes) {
      expect((probe.match(/\?/g) ?? []).length).toBeLessThanOrEqual(UID_PROBE_CHUNK);
    }
    // No unbounded read of the table's uid column.
    expect(iris.sql.some((s) => /SELECT "uid" AS uid FROM SC_Data\."Carrier"$/.test(s))).toBe(false);
  });

  it('uses the column names IRIS reports, not the ones the file\'s header used', async () => {
    // The header matched `NAME` case-insensitively, but what goes into the statement and
    // the staged file is the column's own spelling.
    const iris = createFakeScDataIris({ tables: { Carrier: ['uid', 'NAME', 'type', 'status'] } });
    await loadScDataCsv(iris.deps, { ...CARRIERS, csv: CARRIER_CSV });

    expect(stagedLines(iris.staged('Carrier'))[0]).toBe('uid,NAME,type,status');
    expect(iris.loads()[0]).toContain('("uid","NAME","type","status")');
  });

  it('stages under the configured IRIS directory, one file per table', async () => {
    const { iris } = await load(CARRIER_CSV);
    expect(iris.loads()[0]).toContain("'/tmp/sco-workbench/csv/sample-data/Carrier.csv'");
  });

  it('gives LOAD DATA its OWN long timeout and never retries it', async () => {
    // The bug this exists for: a 1,000-row file took 57s on the real instance, the
    // shared 30s HTTP timeout fired, the request was retried 3× over a statement that
    // was still running, and the user got "timed out after 30000ms" and no report.
    const { iris } = await load(CARRIER_CSV);

    const loadDataCall = iris.calls.find((c) => c.sql.startsWith('LOAD DATA'));
    expect(loadDataCall?.options).toEqual({ timeoutMs: LOAD_TIMEOUT_MS, attempts: 1 });
    // Ten minutes, and nothing the deployment can shorten back to the query timeout.
    expect(LOAD_TIMEOUT_MS).toBeGreaterThan(30_000);
    // Only the load: a schema query keeps the client's own timeout and its retries.
    for (const call of iris.calls.filter((c) => !c.sql.startsWith('LOAD DATA'))) {
      expect(call.options, call.sql).toBeUndefined();
    }
  });

  it("reports IRIS's OWN reason when rows vanish, not just the count", async () => {
    // LOAD DATA answers `status: Complete` and writes the truth to %SQL_Diag, so
    // without reading that back the user gets a number and no way to act on it.
    const iris = createFakeScDataIris({
      onLoad: () => [],
      diag: {
        errorCount: 2,
        messages: [
          "Batch row: 0 [SQLCODE: <-121>:<...>] Table 'SC_Data.Carrier' ...",
          "Table 'SC_Data.Carrier', Foreign Key Constraint 'carrierIdFK', Field(s) UID failed referential integrity check",
        ],
      },
    });
    const error = await failedLoad(iris);
    // The reason is a SECOND LINE under the outcome, not a clause tacked onto it.
    expect(error.message).toMatch(
      /^Sent 2 row\(s\) to SC_Data\.Carrier, 0 loaded\. Data loading for this table failed\.\nSCO rejected at least 2 row\(s\): Table 'SC_Data\.Carrier', Foreign Key Constraint 'carrierIdFK'/,
    );
    // The `Batch row: 0 …` line says the SAME thing once per rejected row, so it is not
    // reported next to the sentence it prefixes — only when nothing else says it.
    expect(error.message).not.toContain('Batch row');
  });

  it('reports a reason that arrives ONLY as a Batch row line', async () => {
    // This is the "IRIS rejected 104 row(s), without saying why" a load hit on an
    // already-populated instance: for a batched rejection the reason exists in no other
    // form, so dropping every `Batch row:` line dropped the only copy of it.
    const iris = createFakeScDataIris({
      onLoad: () => [],
      diag: {
        errorCount: 104,
        messages: [
          "Batch row: 1 [SQLCODE: <-104>:<Field validation failed>] Field 'SC_Data.Carrier.uid' (value 'CAR-1') failed validation",
          "Batch row: 2 [SQLCODE: <-104>:<Field validation failed>] Field 'SC_Data.Carrier.uid' (value 'CAR-2') failed validation",
        ],
      },
    });
    const error = await failedLoad(iris);

    expect(error.message).toContain('[SQLCODE: <-104>');
    expect(error.message).toContain('failed validation');
    // A reason reached the user, so there IS a second line.
    expect(error.message.split('\n')).toHaveLength(2);
    // Stripped rather than quoted whole: the row number is the one part of the line that
    // is different every time, and it is the part that says nothing.
    expect(error.message).not.toContain('Batch row');
  });

  it('keeps a reason IRIS filed under sqlcode 0', async () => {
    // The old query asked for `sqlcode <> 0`, which threw the reason away whenever IRIS
    // put the code in the message TEXT instead of the column.
    const iris = createFakeScDataIris({
      onLoad: () => [],
      diag: {
        errorCount: 3,
        messages: [
          { message: 'Loading data into table SC_Data.Carrier', sqlcode: 0 },
          {
            message:
              "[SQLCODE: <-119>] Table 'SC_Data.Carrier', Unique constraint 'CarrierNameIdx' failed",
            sqlcode: 0,
          },
        ],
      },
    });
    await expect(loadScDataCsv(iris.deps, { ...CARRIERS, csv: CARRIER_CSV })).rejects.toThrow(
      /Unique constraint 'CarrierNameIdx' failed/,
    );
  });

  it('adds NO second line when the diagnostics carry no reason', async () => {
    // A progress line is not a cause. There is an error count here (2) and it is still
    // not reported: a count with no reason behind it says nothing the first line did not
    // already say, and reads like a second, separate finding.
    const iris = createFakeScDataIris({
      onLoad: () => [],
      diag: {
        errorCount: 2,
        messages: [{ message: 'Loading data into table SC_Data.Carrier', sqlcode: 0 }],
      },
    });
    const error = await failedLoad(iris);

    expect(error.message).toBe(
      'Sent 2 row(s) to SC_Data.Carrier, 0 loaded. Data loading for this table failed.',
    );
    expect(error.message).not.toContain('\n');
  });

  it('still reports the outcome when %SQL_Diag itself cannot be read', async () => {
    // The diagnosis is a nicety; losing it must not replace the real complaint with a
    // complaint about diagnostics.
    const iris = createFakeScDataIris({ onLoad: () => [], failOn: /%SQL_Diag/ });
    const error = await failedLoad(iris);

    expect(error.message).toBe(
      'Sent 2 row(s) to SC_Data.Carrier, 0 loaded. Data loading for this table failed.',
    );
  });

  it('REFUSES a staging directory that would break out of the SQL string literal', async () => {
    // The path is interpolated into LOAD DATA's file literal, so a quote is rejected
    // rather than escaped.
    const iris = createFakeScDataIris();
    const deps: ScDataLoadDeps = { ...iris.deps, stageDir: "/tmp/it's" };
    await expect(loadScDataCsv(deps, { ...CARRIERS, csv: CARRIER_CSV })).rejects.toThrow(
      /not a usable path inside SCO/,
    );
    expect(iris.loads()).toEqual([]);
  });
});

/** A fake whose LOAD DATA fails, for the cleanup test. */
function createFailingLoad() {
  const iris = createFakeScDataIris({ failOn: /^LOAD DATA/ });
  return { iris };
}

// ---------------------------------------------------------------------------
// Rows whose FOREIGN KEY has no parent.
//
// SC_Data's foreign keys are real, and `LOAD DATA` enforces them: it rejects the
// violating row with SQLCODE -121, reports `status: Complete` anyway, and ignores the
// `maxErrorCount` that would have made it stop. On the real instance a customers.csv
// whose locations were absent spent 57 SECONDS rejecting all 1,019 of its rows, blew
// the HTTP timeout, and cost the user the report for the whole set. So the rows are
// checked HERE first — the same rule the user set for a duplicate uid ("ignore that row
// and continue with the others"), applied to a missing parent.
// ---------------------------------------------------------------------------
describe('loadScDataCsv and referential integrity', () => {
  const CUSTOMERS = { file: 'customers.csv', table: 'Customer' };
  /** Two customers in the location the fake's `existing` puts in Location. */
  const CUSTOMER_CSV = [
    'ID,Name,Type,Status,primaryLocationId',
    'CUS-1,Acme,Retail,Active,LOC-1',
    'CUS-2,Globex,Retail,Active,LOC-MISSING',
  ].join('\n') + '\n';

  /** The one foreign key customers.csv fills, as SC_Data really declares it. */
  const CUSTOMER_FKS = {
    Customer: [
      { column: 'primaryLocationId', parentTable: 'Location', constraint: 'primaryLocationIdFK' },
    ],
  };

  it('leaves out the row whose parent is missing and loads the one whose parent is there', async () => {
    const { result, iris } = await load(CUSTOMER_CSV, CUSTOMERS, {
      foreignKeys: CUSTOMER_FKS,
      existing: { Location: ['LOC-1'] },
    });

    expect(result).toMatchObject({ loaded: true, rows: 1, skippedRows: 0, orphanRows: 1, totalRows: 2 });
    expect(iris.rows('Customer')).toEqual(['CUS-1']);
    expect(stagedLines(iris.staged('Customer'))).not.toContain(
      'CUS-2,Globex,Retail,Active,LOC-MISSING',
    );
  });

  it('names the missing reference, the constraint and an example value', async () => {
    // "0 rows arrived" tells the user nothing they can act on; the file that has to be
    // added to the set does.
    const { result } = await load(CUSTOMER_CSV, CUSTOMERS, {
      foreignKeys: CUSTOMER_FKS,
      existing: { Location: ['LOC-1'] },
    });

    expect(result).toMatchObject({ orphanReason: expect.stringContaining('SC_Data.Location') });
    const reason = (result as { orphanReason?: string }).orphanReason ?? '';
    expect(reason).toContain('1 row(s)');
    expect(reason).toContain('LOC-MISSING');
    expect(reason).toContain('primaryLocationIdFK');
  });

  it('refuses the whole file WITHOUT a load when the parent table is empty', async () => {
    // The user's actual failure: a set with no locations.csv, so SC_Data.Location is
    // empty and every row of every location-referencing file is an orphan. This is the
    // case that used to cost minutes per file.
    const { result, iris } = await load(CUSTOMER_CSV, CUSTOMERS, { foreignKeys: CUSTOMER_FKS });

    expect(result).toMatchObject({ loaded: true, rows: 0, orphanRows: 2, totalRows: 2 });
    expect(iris.loads()).toEqual([]);
    expect(iris.files.size).toBe(0);
    // Answered by ONE emptiness test, not by asking about every value in the file.
    expect(iris.sql.some((s) => /SELECT TOP 1 "uid" AS value FROM SC_Data\."Location"/.test(s))).toBe(
      true,
    );
    expect(iris.sql.some((s) => s.includes('FROM SC_Data."Location" WHERE "uid" IN ('))).toBe(false);
  });

  it('treats a BLANK foreign key as fine, because SC_Data lets it be null', async () => {
    const csv = 'ID,Name,Type,Status,primaryLocationId\nCUS-1,Acme,Retail,Active,\n';
    const { result, iris } = await load(csv, CUSTOMERS, {
      foreignKeys: CUSTOMER_FKS,
      existing: { Location: ['LOC-1'] },
    });

    expect(result).toMatchObject({ rows: 1, orphanRows: 0 });
    expect(iris.rows('Customer')).toEqual(['CUS-1']);
  });

  it('does not check a foreign key whose column this file never fills', async () => {
    // customers.csv has no shipToLocationId header, so that column stays NULL and there
    // is nothing to check — asking anyway would cost a round trip per file for nothing.
    const { result } = await load(CUSTOMER_CSV, CUSTOMERS, {
      foreignKeys: {
        Customer: [
          ...CUSTOMER_FKS.Customer,
          { column: 'shipToLocationId', parentTable: 'Location' },
        ],
      },
      existing: { Location: ['LOC-1'] },
    });

    expect(result).toMatchObject({ rows: 1, orphanRows: 1 });
    expect((result as { orphanReason?: string }).orphanReason).not.toContain('shipToLocationId');
  });

  it('accepts a SELF-reference satisfied by a row from the same file', async () => {
    // SalesShipment.parentShipmentId → SalesShipment.uid: the parent lands in this very
    // load, so dropping the child would be wrong.
    const shipments = { file: 'salesShipments.csv', table: 'SalesShipment' };
    const csv = [
      'ID,customerId,Status,parentShipmentId',
      'SHP-1,CUS-1,Active,',
      'SHP-2,CUS-1,Active,SHP-1',
      'SHP-3,CUS-1,Active,SHP-NOPE',
    ].join('\n') + '\n';
    const { result, iris } = await load(csv, shipments, {
      tables: { SalesShipment: ['uid', 'customerId', 'status', 'parentShipmentId'] },
      foreignKeys: { SalesShipment: [{ column: 'parentShipmentId', parentTable: 'SalesShipment' }] },
      existing: { SalesShipment: ['SHP-0'] },
    });

    expect(result).toMatchObject({ rows: 2, orphanRows: 1 });
    expect(iris.rows('SalesShipment')).toEqual(['SHP-0', 'SHP-1', 'SHP-2']);
  });

  it('IGNORES a composite foreign key instead of checking its columns one by one', async () => {
    // Two columns that are only meaningful together: a row whose values each exist
    // separately, but not as a pair, must not be judged here. IRIS still enforces it.
    const { result, iris } = await load(CUSTOMER_CSV, CUSTOMERS, {
      foreignKeys: {
        Customer: [
          { column: 'primaryLocationId', parentTable: 'Location', constraint: 'compositeFK' },
          { column: 'name', parentTable: 'Location', constraint: 'compositeFK' },
        ],
      },
      existing: { Location: ['LOC-1'] },
    });

    expect(result).toMatchObject({ rows: 2, orphanRows: 0 });
    expect(iris.rows('Customer')).toEqual(['CUS-1', 'CUS-2']);
  });

  it('checks nothing when the table has no foreign keys at all', async () => {
    const { result, iris } = await load(CARRIER_CSV);
    expect(result).toMatchObject({ rows: 2, orphanRows: 0 });
    expect(iris.sql.some((s) => /SELECT TOP 1 "[^"]+" AS value/.test(s))).toBe(false);
    expect(iris.sql.some((s) => s.includes('KEY_COLUMN_USAGE'))).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Values that are right for the column's NAME and wrong for its TYPE.
//
// `SC_Data.BOM.isAlternate` is a BIT: IRIS stores only 1 or 0 there and fails
// validation on anything else, per row — `Field 'SC_Data.BOM.isAlternate' (value 'No')
// failed validation`, measured 2026-09-08 on the generator's BOM.csv, which writes
// Yes/No for all 5,103 rows. Left alone that cost the file its whole load: IRIS ground
// through it for minutes until the web gateway answered HTTP 504.
// ---------------------------------------------------------------------------
describe('loadScDataCsv and column types', () => {
  const BOM = { file: 'BOM.csv', table: 'BOM' };
  /** BOM.csv's header: the table's own column names, keyed on `ID`. */
  const BOM_HEADER = 'ID,productId,itemId,parentItemId,quantity,unitOfMeasure,isAlternate,substituteFor';
  const bomRow = (uid: string, isAlternate: string) =>
    `${uid},PRD-1,ITEM-1,,3,EACH,${isAlternate},`;
  /** BOM as SC_Data really declares it: two BIT columns among the varchars. */
  const BOM_TYPES = { 'BOM.isAlternate': 'BIT', 'BOM.productionRelevant': 'BIT' };

  /** Load a BOM file whose `isAlternate` column holds each given value in turn. */
  async function loadBom(values: string[]) {
    const csv = [BOM_HEADER, ...values.map((v, i) => bomRow(`BOM-${i + 1}`, v))].join('\n') + '\n';
    const { result, iris } = await load(csv, BOM, { columnTypes: BOM_TYPES });
    const at = stagedLines(iris.staged('BOM'))[0]?.split(',').indexOf('isAlternate') ?? -1;
    return {
      result,
      iris,
      /** What each staged row now holds in its isAlternate cell. */
      staged: stagedLines(iris.staged('BOM')).slice(1).map((line) => line.split(',')[at]),
    };
  }

  it('sends 1 and 0 to a BIT column for the words a CSV writes a boolean with', async () => {
    const { result, staged } = await loadBom([
      'No', 'Yes', 'no', 'YES', 'true', 'False', 'Y', 'n', '1', '0',
    ]);

    expect(result).toMatchObject({ rows: 10, orphanRows: 0 });
    expect(staged).toEqual(['0', '1', '0', '1', '1', '0', '1', '0', '1', '0']);
  });

  it('stages a BLANK boolean empty, leaving the meaning of "not stated" to IRIS', async () => {
    // There is no boolean word to convert, so nothing is invented here; a `bit` column
    // gets the same empty cell every other column would. (On the live instance IRIS's
    // own `LOAD DATA` then stores 0.) Spaces are not a boolean either, so they go the
    // same way rather than reaching IRIS and failing validation.
    const { staged } = await loadBom(['', '   ']);
    expect(staged).toEqual(['', '']);
  });

  it('passes a value it does not recognise THROUGH, for IRIS to judge', async () => {
    // Inventing a 0 for "Maybe" would store data the file never contained. IRIS
    // rejects that row and %SQL_Diag says why — which is the honest outcome.
    const { staged } = await loadBom(['Maybe', '2']);
    expect(staged).toEqual(['Maybe', '2']);
  });

  it('touches only the BIT column: a VARCHAR keeps the word the file wrote', async () => {
    // `unitOfMeasure` is a varchar, and 'No' in one would be a real value.
    const csv = [BOM_HEADER, 'BOM-1,PRD-1,ITEM-1,,3,No,Yes,'].join('\n') + '\n';
    const { iris } = await load(csv, BOM, { columnTypes: BOM_TYPES });
    const [header, row] = stagedLines(iris.staged('BOM'));
    const cell = (name: string) => row?.split(',')[header?.split(',').indexOf(name) ?? -1];

    expect(cell('unitOfMeasure')).toBe('No'); // untouched
    expect(cell('isAlternate')).toBe('1'); // converted
  });

  it('reads each column\'s type from IRIS, so the same file suits either namespace', async () => {
    // The same file against a namespace where isAlternate is a plain varchar: the word
    // is what the column takes, so nothing is converted.
    const csv = [BOM_HEADER, bomRow('BOM-1', 'No')].join('\n') + '\n';
    const { iris } = await load(csv, BOM, {});
    const [header, row] = stagedLines(iris.staged('BOM'));
    expect(row?.split(',')[header?.split(',').indexOf('isAlternate') ?? -1]).toBe('No');
    // And the type really came from the column query.
    expect(iris.sql.some((s) => s.includes('DATA_TYPE') && s.includes('INFORMATION_SCHEMA.COLUMNS'))).toBe(true);
  });
});
